[package]
name = "captures-image"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
captures-history = { path = "../captures-history" }
image.workspace = true
jpeg-encoder = "0.6"
png = "0.17"
quantette = { version = "0.6", default-features = false, features = ["image", "std", "threads"] }
webp = { version = "0.3", default-features = false }
tiny-skia = { version = "0.11", default-features = false, features = ["std", "simd"] }
fontdue = "0.9"

[lints]
workspace = true
