[package]
name = "captures-image"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
image.workspace = true
tiny-skia = { version = "0.11", default-features = false, features = ["std", "simd"] }
fontdue = "0.9"

[lints]
workspace = true
